In [6]:
import numpy as np

# 1D array
arr_1d = np.array([10, 20, 30, 40, 50, 60])
print("1D array:", arr_1d)
print("Shape:", arr_1d.shape)

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D array:\n", arr_2d)
print("Shape:", arr_2d.shape)

# Reshape: 1D -> 2D
reshaped = arr_1d.reshape(2, 3)
print("\nReshaped 1D into 2x3:\n", reshaped)

# Reshape: 2D -> 1D (flatten)
flattened = arr_2d.flatten()
print("\nFlattened 2D array:", flattened)

# Slicing - 1D
print("\nSlice arr_1d[1:4]:", arr_1d[1:4])      # elements index 1 to 3
print("Slice arr_1d[::2]:", arr_1d[::2])         # every 2nd element

# Slicing - 2D
print("\narr_2d[0:2, 2:3]:\n", arr_2d[0:2, 2:3])  # rows 0-1, cols 1-2
print("\narr_2d[:, 0]:", arr_2d[:, 0])             # first column
print("arr_2d[1, :]:", arr_2d[1, :])               # second row

# Broadcasting
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
print("\nBroadcasting a (1x3) + b (3x1):\n", a + b)

scalar_mult = arr_2d * 2
print("\narr_2d * 2:\n", scalar_mult)

# Broadcasting with mismatched shapes (row-wise add)
row_add = arr_2d + np.array([100, 200, 300])
print("\narr_2d + [100,200,300] (row broadcast):\n", row_add)

1D array: [10 20 30 40 50 60]
Shape: (6,)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

Reshaped 1D into 2x3:
 [[10 20 30]
 [40 50 60]]

Flattened 2D array: [1 2 3 4 5 6 7 8 9]

Slice arr_1d[1:4]: [20 30 40]
Slice arr_1d[::2]: [10 30 50]

arr_2d[0:2, 2:3]:
 [[3]
 [6]]

arr_2d[:, 0]: [1 4 7]
arr_2d[1, :]: [4 5 6]

Broadcasting a (1x3) + b (3x1):
 [[11 12 13]
 [21 22 23]
 [31 32 33]]

arr_2d * 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

arr_2d + [100,200,300] (row broadcast):
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [9]:
def compute_stats(nums):
  n = len(nums)
  if n == 0:
    return None

  total = sum(nums)
  #mean
  mean = total / n

  #median
  sorted_num = sorted(nums)
  mid = n // 2
  if n % 2 == 0:
    median = (sorted_num[mid - 1] + sorted_num[mid]) / 2
  else:
    median = sorted_num[mid]

  #Standard deviation
  variance = sum((x - mean) ** 2 for x in nums) / n
  std_dev = variance ** 0.5

  return {
      "mean": mean,
      "median": median,
      "std_dev": std_dev
  }

data = [23, 42, 34, 12, 10, 1, 21, 90, 83]

result = compute_stats(data)
print("Manual results")
print(f"Mean: {result['mean']:.4f}")
print(f"Median: {result['median']:.4f}")
print(f"std_dev: {result['std_dev']:.4f}")

#verify with numpy
np_arr = np.array(data)
print('\nNumpy Results')
print(f'Mean: {np.mean(np_arr):.4f}')
print(f'Median: {np.median(np_arr):.4f}')
print(f"Std_dev: {np.std(np_arr)}")

#Sanity Check
print('\nSanity Check:',
      abs(result['mean'] - np.mean(np_arr)) < 1e-9 and
      abs(result['median'] - np.median(np_arr)) < 1e-9 and
      abs(result['std_dev'] - np.std(np_arr)) < 1e-9
)

Manual results
Mean: 35.1111
Median: 23.0000
std_dev: 29.8680

Numpy Results
Mean: 35.1111
Median: 23.0000
Std_dev: 29.86802245599964

Sanity Check: True


In [10]:
#fizzbuzz
for i in range(1, 51):
  if i % 15 == 0:
    print("FizzBuzz")
  elif i % 3 == 0:
    print("Fizz")
  elif i % 5 == 0:
    print("Buzz")
  else:
    print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [11]:
#Palindrome
def is_pal(str):
  clean_str  = str.lower().replace(" ", "")
  return clean_str == clean_str[::-1]

print(is_pal("racecar"))
print(is_pal("hello"))

True
False


In [12]:
#Squares of even number
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_sqr = [i ** 2 for i in nums if i % 2 == 0]
print(even_sqr)

[4, 16, 36, 64, 100]


In [13]:
def word_freq(sentence):
  words = sentence.lower().split()
  freq_dict = {}
  for w in words:
    freq_dict[w] = freq_dict.get(w, 0) + 1
  return freq_dict

print(word_freq("the quick brown fox jumps over the lazy dog the fox runs"))

{'the': 3, 'quick': 1, 'brown': 1, 'fox': 2, 'jumps': 1, 'over': 1, 'lazy': 1, 'dog': 1, 'runs': 1}


In [14]:
students = [
    {"name": "Asha", "marks": 88},
    {"name": "Ravi", "marks": 92},
    {"name": "Meena", "marks": 79},
    {"name": "Karan", "marks": 95},
]
topper_student = students[0]
for s in students:
  if s["marks"] > topper_student["marks"]:
    topper_student = s
print("Manual: ", topper_student)

print(f"The topper is {topper_student['name']} with {topper_student['marks']} marks")
topper_verified = max(students, key=lambda x: x["marks"])
print(f"Verified, {topper_verified}")


Manual:  {'name': 'Karan', 'marks': 95}
The topper is Karan with 95 marks
Verified, {'name': 'Karan', 'marks': 95}
