In [1]:
#Aggregation along axes
import numpy as np
import pandas as pd
import time

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Sum of matrix: ", matrix.sum())
print("Sum of  (axis=0, column): ", matrix.sum(axis=0))
print("Sum of  (axis=1, row): ", matrix.sum(axis=1))
print("Max along (axis=0): ", matrix.max(axis=0))
print("Max along (axis=1): ", matrix.max(axis=1))
print("Min along (axis=0): ", matrix.min(axis=0))
print("Min along (axis=1): ", matrix.min(axis=1))
print("Cumulative sum: ", matrix.cumsum())

Sum of matrix:  45
Sum of  (axis=0, column):  [12 15 18]
Sum of  (axis=1, row):  [ 6 15 24]
Max along (axis=0):  [7 8 9]
Max along (axis=1):  [3 6 9]
Min along (axis=0):  [1 2 3]
Min along (axis=1):  [1 4 7]
Cumulative sum:  [ 1  3  6 10 15 21 28 36 45]


In [2]:
#Vectorization and Looping
n = 1_000_000
arr = np.arange(n)

start = time.time()
res_loop = [x ** 2 for x in arr]
loop_time = time.time() - start

start = time.time()
result_vec = arr ** 2
vec_time = time.time() - start

print(f"\nLooping time: {loop_time:.4f}s")
print(f"\nVectorized time: {vec_time:.4f}s")
print(f"Speedup: {loop_time/vec_time:.1f}x faster")


Looping time: 0.1478s

Vectorized time: 0.0029s
Speedup: 51.0x faster


In [8]:
#Matrix Operation
A = np.array([[1,2], [3,4]])
B = np.array([[5,6],[7,8]])
print("Dot product of matrix (A . B): \n", np.dot(A, B))
print("\nMatrix multiply A @ B\n", A @ B)
print("\nTranspose matrix: \n", A.T)
print("\nIdentity matrix {3 * 3}: \n", np.eye(3))
print("\nInverse matrix:\n", np.linalg.inv(A))
print("\nDeterminant of A:", np.linalg.det(A))

Dot product of matrix (A . B): 
 [[19 22]
 [43 50]]

Matrix multiply A @ B
 [[19 22]
 [43 50]]

Transpose matrix: 
 [[1 3]
 [2 4]]

Identity matrix {3 * 3}: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Inverse matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A: -2.0000000000000004
